---
version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.authc.api_key.enabled=true
      - xpack.security.enabled=$ELASTIC_SECURITY
      - xpack.security.authc.realms.native.native1.order=0
    volumes:
      - ${HOME}/tmp/elk-basic:/var/lib/elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    volumes:
      - ${PWD}/kibana.noauth.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    ports: ['5601:5601']
    networks: ['stack']
    links: ['elasticsearch']
    #links: ['elasticsearch','workplace']
    #depends_on: ['elasticsearch','workplace']
    depends_on: ['elasticsearch']

networks:
  stack: {}
