---
version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    volumes:
      - ${PWD}/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ${PWD}/certs/tls.pem:/certs/tls.pem
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    ports: ['5601:5601']
    networks: ['stack']
networks:
  stack: {}
